version: '2'
services:
    bucky:
     build:
      context: bucky
     ports:
      - 80:80
     depends_on:
     - influx
     environment:
      - BUCKY_PORT=80
      - INFLUXDB_USERNAME=root
      - INFLUXDB_PASSWORD=root
      - INFLUXDB_DATABASE=bucky
      - INFLUXDB_HOST=influx
      - INFLUXDB_PORT=8086

     links:
      - influx:influx

    influx:
     image: influxdb:1.1

